use db_pedido;

CREATE TABLE PRODUTO(
	ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    DESCRICAO VARCHAR (60) NOT NULL,
    DATA_CADASTRO timestamp DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO PRODUTO (DESCRICAO) VALUES ('PIZZA GRANDE' );

